# railway.toml
[build]
builder = "nixpacks"

[[services]]
name = "worker-loop"
startCommand = "npm run loop"
[services.deploy]
restartPolicyType = "always"
restartPolicyMaxRetries = 10

[[services]]
name = "worker-brand"
startCommand = "npm run brand"
[services.deploy]
cronSchedule = "3,23,43 * * * *"
restartPolicyType = "never"

[[services]]
name = "worker-report"
startCommand = "npm run report"
[services.deploy]
cronSchedule = "0 * * * *"
restartPolicyType = "never"
