// GENERATED — do not edit manually
// Source: Shopify Standard Product Taxonomy 2026-02
// Generated by: node scripts/fetch-taxonomy.js
// Re-run quarterly when Shopify releases a new taxonomy version.
// https://github.com/Shopify/product-taxonomy

export const TAXONOMY_VERSION = '2026-02'

// Maps full taxonomy path → Google Shopping category ID
// Shopify Category field stores the full path string (used by Matrixify)
// Google category is derived automatically from the same lookup — no separate Claude call needed
export const TAXONOMY = {
  // ── Apparel & Accessories ──────────────────────────────────────────────────
  'Apparel & Accessories': '166',
  'Apparel & Accessories > Clothing': '166',
  'Apparel & Accessories > Clothing > Activewear': '5322',
  'Apparel & Accessories > Clothing > Activewear > Sports Bras': '5322',
  'Apparel & Accessories > Clothing > Activewear > Athletic Shorts': '5322',
  'Apparel & Accessories > Clothing > Activewear > Athletic Pants': '5322',
  'Apparel & Accessories > Clothing > Bras': '2306',
  'Apparel & Accessories > Clothing > Dresses': '2271',
  'Apparel & Accessories > Clothing > Jumpsuits & Rompers': '166',
  'Apparel & Accessories > Clothing > Outerwear': '166',
  'Apparel & Accessories > Clothing > Outerwear > Jackets & Coats': '166',
  'Apparel & Accessories > Clothing > Pants': '2368',
  'Apparel & Accessories > Clothing > Shirts & Tops': '212',
  'Apparel & Accessories > Clothing > Shirts & Tops > T-Shirts': '212',
  'Apparel & Accessories > Clothing > Shirts & Tops > Tank Tops': '212',
  'Apparel & Accessories > Clothing > Shorts': '207',
  'Apparel & Accessories > Clothing > Skirts': '208',
  'Apparel & Accessories > Clothing > Sleepwear & Loungewear': '214',
  'Apparel & Accessories > Clothing > Socks & Hosiery': '209',
  'Apparel & Accessories > Clothing > Socks & Hosiery > Socks': '209',
  'Apparel & Accessories > Clothing > Suits': '166',
  'Apparel & Accessories > Clothing > Swimwear': '210',
  'Apparel & Accessories > Clothing > Underwear & Intimates': '214',
  'Apparel & Accessories > Clothing > Underwear & Intimates > Bras': '2306',
  'Apparel & Accessories > Clothing > Underwear & Intimates > Underwear': '214',

  // ── Shoes ─────────────────────────────────────────────────────────────────
  'Apparel & Accessories > Shoes': '187',
  'Apparel & Accessories > Shoes > Athletic Shoes': '187',
  'Apparel & Accessories > Shoes > Baby & Toddler Shoes': '187',
  'Apparel & Accessories > Shoes > Boots': '187',
  'Apparel & Accessories > Shoes > Clogs & Mules': '187',
  'Apparel & Accessories > Shoes > Flats': '187',
  'Apparel & Accessories > Shoes > Heels': '187',
  'Apparel & Accessories > Shoes > Loafers': '187',
  'Apparel & Accessories > Shoes > Sandals': '187',
  'Apparel & Accessories > Shoes > Slippers': '187',
  'Apparel & Accessories > Shoes > Sneakers': '187',
  'Apparel & Accessories > Shoes > Water Shoes': '187',
  'Apparel & Accessories > Shoes > Work & Safety Shoes': '187',

  // ── Accessories ───────────────────────────────────────────────────────────
  'Apparel & Accessories > Accessories': '166',
  'Apparel & Accessories > Accessories > Belts': '169',
  'Apparel & Accessories > Accessories > Gloves & Mittens': '170',
  'Apparel & Accessories > Accessories > Hair Accessories': '171',
  'Apparel & Accessories > Accessories > Hats & Caps': '173',
  'Apparel & Accessories > Accessories > Scarves & Shawls': '174',
  'Apparel & Accessories > Accessories > Shoe Accessories': '1933',
  'Apparel & Accessories > Accessories > Shoe Accessories > Insoles & Inserts': '1933',
  'Apparel & Accessories > Accessories > Sunglasses': '178',
  'Apparel & Accessories > Accessories > Ties': '166',
  'Apparel & Accessories > Accessories > Umbrellas': '201',
  'Apparel & Accessories > Accessories > Wallets & Money Clips': '2668',
  'Apparel & Accessories > Accessories > Watches': '201',

  // ── Bags ──────────────────────────────────────────────────────────────────
  'Apparel & Accessories > Handbags, Wallets & Cases': '3032',
  'Apparel & Accessories > Handbags, Wallets & Cases > Backpacks': '3032',
  'Apparel & Accessories > Handbags, Wallets & Cases > Handbags': '3032',
  'Apparel & Accessories > Handbags, Wallets & Cases > Wallets': '2668',

  // ── Jewelry ───────────────────────────────────────────────────────────────
  'Apparel & Accessories > Jewelry': '188',
  'Apparel & Accessories > Jewelry > Bracelets': '188',
  'Apparel & Accessories > Jewelry > Earrings': '188',
  'Apparel & Accessories > Jewelry > Necklaces': '188',
  'Apparel & Accessories > Jewelry > Rings': '188',

  // ── Luggage & Travel ──────────────────────────────────────────────────────
  'Luggage & Travel': '5181',
  'Luggage & Travel > Bags': '3032',
  'Luggage & Travel > Bags > Backpacks': '3032',
  'Luggage & Travel > Bags > Duffel Bags': '3032',
  'Luggage & Travel > Bags > Hydration Packs': '3032',
  'Luggage & Travel > Bags > Messenger & Shoulder Bags': '3032',
  'Luggage & Travel > Bags > Tote Bags': '3032',
  'Luggage & Travel > Luggage': '5181',
  'Luggage & Travel > Luggage > Carry-On Luggage': '5181',
  'Luggage & Travel > Luggage > Checked Luggage': '5181',

  // ── Baby & Toddler ────────────────────────────────────────────────────────
  'Baby & Toddler': '537',
  'Baby & Toddler > Baby Transport': '537',
  'Baby & Toddler > Baby Transport > Baby Carriers': '537',
  'Baby & Toddler > Baby Transport > Strollers': '537',
  'Baby & Toddler > Diapering': '537',
  'Baby & Toddler > Feeding': '537',
  'Baby & Toddler > Feeding > Baby Bottles': '537',
  'Baby & Toddler > Nursery': '537',
  'Baby & Toddler > Toys': '537',

  // ── Electronics ───────────────────────────────────────────────────────────
  'Electronics': '222',
  'Electronics > Audio': '2082',
  'Electronics > Audio > Headphones': '2082',
  'Electronics > Audio > Portable Speakers': '2082',
  'Electronics > Audio > Smart Speakers': '2082',
  'Electronics > Cameras & Optics': '222',
  'Electronics > Communications': '222',
  'Electronics > Computers': '328',
  'Electronics > Computers > Tablets': '328',
  'Electronics > Electronics Accessories': '222',
  'Electronics > Electronics Accessories > Cables': '222',
  'Electronics > Electronics Accessories > Chargers': '222',
  'Electronics > GPS & Navigation': '222',
  'Electronics > Smart Home Devices': '222',
  'Electronics > TV & Home Theater': '222',
  'Electronics > Video Game Consoles & Games': '222',
  'Electronics > Video Game Consoles & Games > Gaming Accessories': '222',

  // ── Food, Beverages & Tobacco ─────────────────────────────────────────────
  'Food, Beverages & Tobacco': '422',
  'Food, Beverages & Tobacco > Beverages': '413',
  'Food, Beverages & Tobacco > Food Items': '422',

  // ── Furniture ─────────────────────────────────────────────────────────────
  'Furniture': '436',
  'Furniture > Bedroom Furniture': '436',
  'Furniture > Office Furniture': '436',

  // ── Hardware ──────────────────────────────────────────────────────────────
  'Hardware': '632',
  'Hardware > Locks & Keys': '632',
  'Hardware > Safety & Security': '632',
  'Hardware > Tools': '632',

  // ── Health & Beauty ───────────────────────────────────────────────────────
  'Health & Beauty': '491',
  'Health & Beauty > Health Care': '491',
  'Health & Beauty > Health Care > First Aid': '491',
  'Health & Beauty > Health Care > Fitness & Nutrition': '491',
  'Health & Beauty > Health Care > Fitness & Nutrition > Vitamins & Supplements': '491',
  'Health & Beauty > Health Care > Medical Aids & Equipment': '491',
  'Health & Beauty > Health Care > Medical Aids & Equipment > Insoles & Orthotics': '1933',
  'Health & Beauty > Personal Care': '567',
  'Health & Beauty > Personal Care > Bath & Body': '567',
  'Health & Beauty > Personal Care > Bath & Body > Body Wash & Shower Gel': '567',
  'Health & Beauty > Personal Care > Bath & Body > Lotions & Moisturizers': '567',
  'Health & Beauty > Personal Care > Deodorant & Antiperspirant': '567',
  'Health & Beauty > Personal Care > Hair Care': '486',
  'Health & Beauty > Personal Care > Hair Care > Shampoo': '486',
  'Health & Beauty > Personal Care > Hair Care > Conditioner': '486',
  'Health & Beauty > Personal Care > Makeup': '491',
  'Health & Beauty > Personal Care > Nail Care': '491',
  'Health & Beauty > Personal Care > Oral Care': '526',
  'Health & Beauty > Personal Care > Oral Care > Toothbrushes': '526',
  'Health & Beauty > Personal Care > Shaving & Grooming': '567',
  'Health & Beauty > Personal Care > Skin Care': '567',

  // ── Home & Garden ─────────────────────────────────────────────────────────
  'Home & Garden': '536',
  'Home & Garden > Bathroom Accessories': '536',
  'Home & Garden > Bathroom Accessories > Bathroom Hardware': '536',
  'Home & Garden > Bathroom Accessories > Towels': '536',
  'Home & Garden > Bedding': '569',
  'Home & Garden > Bedding > Pillows': '569',
  'Home & Garden > Bedding > Sheets & Pillowcases': '569',
  'Home & Garden > Cleaning Supplies': '623',
  'Home & Garden > Decor': '536',
  'Home & Garden > Decor > Candles & Holders': '536',
  'Home & Garden > Decor > Clocks': '536',
  'Home & Garden > Decor > Figurines & Collectibles': '536',
  'Home & Garden > Decor > Vases': '536',
  'Home & Garden > Kitchen & Dining': '638',
  'Home & Garden > Kitchen & Dining > Bakeware': '638',
  'Home & Garden > Kitchen & Dining > Cookware': '638',
  'Home & Garden > Kitchen & Dining > Cutlery & Flatware': '638',
  'Home & Garden > Kitchen & Dining > Drinkware': '649',
  'Home & Garden > Kitchen & Dining > Drinkware > Mugs': '649',
  'Home & Garden > Kitchen & Dining > Drinkware > Tumblers & Water Bottles': '649',
  'Home & Garden > Kitchen & Dining > Kitchen Appliances': '638',
  'Home & Garden > Kitchen & Dining > Kitchen Appliances > Grills & Outdoor Cooking': '638',
  'Home & Garden > Kitchen & Dining > Kitchen Appliances > Grills & Outdoor Cooking > Pizza Ovens': '638',
  'Home & Garden > Kitchen & Dining > Kitchen Appliances > Small Kitchen Appliances': '638',
  'Home & Garden > Kitchen & Dining > Kitchen Tools & Gadgets': '638',
  'Home & Garden > Kitchen & Dining > Serveware': '638',
  'Home & Garden > Kitchen & Dining > Serveware > Plates & Dishes': '638',
  'Home & Garden > Kitchen & Dining > Storage & Organization': '638',
  'Home & Garden > Lighting': '536',
  'Home & Garden > Lighting > Lamps': '536',
  'Home & Garden > Lighting > Smart Lighting': '536',
  'Home & Garden > Rugs': '536',
  'Home & Garden > Storage & Organization': '536',

  // ── Media ─────────────────────────────────────────────────────────────────
  'Media': '784',
  'Media > Books': '784',
  'Media > Books > Children\'s Books': '784',
  'Media > Books > Educational Books': '784',
  'Media > Movies & Music': '784',
  'Media > Video Games': '784',

  // ── Office Supplies ───────────────────────────────────────────────────────
  'Office Supplies': '922',
  'Office Supplies > Art & Crafts Supplies': '16',
  'Office Supplies > Art & Crafts Supplies > Art Supplies': '16',
  'Office Supplies > Art & Crafts Supplies > Craft Supplies': '16',
  'Office Supplies > Desk Accessories': '922',
  'Office Supplies > Paper Products': '922',
  'Office Supplies > Writing Instruments': '922',

  // ── Pet Supplies ──────────────────────────────────────────────────────────
  'Animals & Pet Supplies': '1',
  'Animals & Pet Supplies > Pet Supplies': '1',
  'Animals & Pet Supplies > Pet Supplies > Cat Supplies': '4',
  'Animals & Pet Supplies > Pet Supplies > Dog Supplies': '3',
  'Animals & Pet Supplies > Pet Supplies > Dog Supplies > Dog Beds': '3',
  'Animals & Pet Supplies > Pet Supplies > Dog Supplies > Dog Food': '3',
  'Animals & Pet Supplies > Pet Supplies > Dog Supplies > Dog Pads': '3',
  'Animals & Pet Supplies > Pet Supplies > Dog Supplies > Dog Treats': '3',
  'Animals & Pet Supplies > Pet Supplies > Dog Supplies > Dog Vitamins & Supplements': '3',

  // ── Sporting Goods ────────────────────────────────────────────────────────
  'Sporting Goods': '988',
  'Sporting Goods > Athletics': '990',
  'Sporting Goods > Athletics > Athletic Bags': '3032',
  'Sporting Goods > Athletics > Exercise & Fitness': '990',
  'Sporting Goods > Athletics > Exercise & Fitness > Fitness Equipment': '990',
  'Sporting Goods > Athletics > Exercise & Fitness > Yoga & Pilates': '990',
  'Sporting Goods > Athletics > Exercise & Fitness > Yoga & Pilates > Yoga Mats': '990',
  'Sporting Goods > Athletics > Team Sports': '988',
  'Sporting Goods > Athletics > Team Sports > Basketball': '988',
  'Sporting Goods > Athletics > Team Sports > Basketball > Basketballs': '988',
  'Sporting Goods > Outdoor Recreation': '988',
  'Sporting Goods > Outdoor Recreation > Climbing': '988',
  'Sporting Goods > Outdoor Recreation > Cycling': '988',
  'Sporting Goods > Outdoor Recreation > Fishing': '988',
  'Sporting Goods > Outdoor Recreation > Hiking & Camping': '3961',
  'Sporting Goods > Outdoor Recreation > Hiking & Camping > Camping Gear': '3961',
  'Sporting Goods > Outdoor Recreation > Hiking & Camping > Hydration Packs': '3032',
  'Sporting Goods > Outdoor Recreation > Water Sports': '988',
  'Sporting Goods > Winter Sports': '988',

  // ── Toys & Games ──────────────────────────────────────────────────────────
  'Toys & Games': '1249',
  'Toys & Games > Building Toys': '1249',
  'Toys & Games > Building Toys > Building Sets': '1249',
  'Toys & Games > Building Toys > Construction Toys': '1249',
  'Toys & Games > Dolls & Action Figures': '1249',
  'Toys & Games > Games': '1249',
  'Toys & Games > Games > Board Games': '1249',
  'Toys & Games > Games > Card Games': '1249',
  'Toys & Games > Games > Puzzles': '1249',
  'Toys & Games > Outdoor Play': '1249',
  'Toys & Games > Ride-On Toys & Scooters': '1249',
  'Toys & Games > Stuffed Animals & Plush Toys': '1249',
  'Toys & Games > Toy Vehicles': '1249',
  'Toys & Games > Toy Vehicles > Toy Cars & Trucks': '1249',
  'Toys & Games > Toys': '1249',

  // ── Vehicles & Parts ──────────────────────────────────────────────────────
  'Vehicles & Parts': '913',
  'Vehicles & Parts > Vehicle Accessories': '913',
  'Vehicles & Parts > Vehicle Parts & Accessories': '913',
}

// Normalize a taxonomy path for fuzzy matching
// Strips extra spaces and normalizes ampersands
export function normalizePath(path) {
  return path?.trim().replace(/\s*>\s*/g, ' > ').replace(/&amp;/g, '&') || ''
}

// Look up Google category ID by full Shopify taxonomy path
// Returns null if not found
export function lookupGoogleCategory(shopifyPath) {
  if (!shopifyPath) return null
  const normalized = normalizePath(shopifyPath)

  // Exact match
  if (TAXONOMY[normalized] !== undefined) return TAXONOMY[normalized]

  // Case-insensitive match
  const lower = normalized.toLowerCase()
  for (const [key, val] of Object.entries(TAXONOMY)) {
    if (key.toLowerCase() === lower) return val
  }

  // Partial match — try progressively shorter paths (walk up the tree)
  const parts = normalized.split(' > ')
  for (let i = parts.length - 1; i > 0; i--) {
    const partial = parts.slice(0, i).join(' > ')
    if (TAXONOMY[partial] !== undefined) return TAXONOMY[partial]
  }

  return null
}
